// Unofficial protobuf definition of Google Authenticator Migration exports
// Based on Google Authenticator 5.10
// Chris van Marle 04-06-2020

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: OtpMigration.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_TYPE_UNSPECIFIED Algorithm = 0
	Algorithm_SHA1                       Algorithm = 1
	Algorithm_SHA256                     Algorithm = 2
	Algorithm_SHA512                     Algorithm = 3
	Algorithm_MD5                        Algorithm = 4
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_TYPE_UNSPECIFIED",
		1: "SHA1",
		2: "SHA256",
		3: "SHA512",
		4: "MD5",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_TYPE_UNSPECIFIED": 0,
		"SHA1":                       1,
		"SHA256":                     2,
		"SHA512":                     3,
		"MD5":                        4,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{0}
}

type DigitCount int32

const (
	DigitCount_DIGIT_COUNT_UNSPECIFIED DigitCount = 0
	DigitCount_SIX                     DigitCount = 1
	DigitCount_EIGHT                   DigitCount = 2
)

// Enum value maps for DigitCount.
var (
	DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "SIX",
		2: "EIGHT",
	}
	DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"SIX":                     1,
		"EIGHT":                   2,
	}
)

func (x DigitCount) Enum() *DigitCount {
	p := new(DigitCount)
	*p = x
	return p
}

func (x DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[1].Descriptor()
}

func (DigitCount) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[1]
}

func (x DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigitCount.Descriptor instead.
func (DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{1}
}

type OtpType int32

const (
	OtpType_OTP_TYPE_UNSPECIFIED OtpType = 0
	OtpType_HOTP                 OtpType = 1
	OtpType_TOTP                 OtpType = 2
)

// Enum value maps for OtpType.
var (
	OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "HOTP",
		2: "TOTP",
	}
	OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"HOTP":                 1,
		"TOTP":                 2,
	}
)

func (x OtpType) Enum() *OtpType {
	p := new(OtpType)
	*p = x
	return p
}

func (x OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[2].Descriptor()
}

func (OtpType) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[2]
}

func (x OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpType.Descriptor instead.
func (OtpType) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{2}
}

type MigrationPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtpParameters []*OtpParameters `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	Version       *int32           `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	BatchSize     *int32           `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3,oneof" json:"batch_size,omitempty"`
	BatchIndex    *int32           `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3,oneof" json:"batch_index,omitempty"`
	BatchId       *int32           `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3,oneof" json:"batch_id,omitempty"`
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OtpMigration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_OtpMigration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpParameters() []*OtpParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *MigrationPayload) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *MigrationPayload) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *MigrationPayload) GetBatchIndex() int32 {
	if x != nil && x.BatchIndex != nil {
		return *x.BatchIndex
	}
	return 0
}

func (x *MigrationPayload) GetBatchId() int32 {
	if x != nil && x.BatchId != nil {
		return *x.BatchId
	}
	return 0
}

type OtpParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret    []byte      `protobuf:"bytes,1,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	Name      *string     `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Issuer    *string     `protobuf:"bytes,3,opt,name=issuer,proto3,oneof" json:"issuer,omitempty"`
	Algorithm *Algorithm  `protobuf:"varint,4,opt,name=algorithm,proto3,enum=Algorithm,oneof" json:"algorithm,omitempty"`
	Digits    *DigitCount `protobuf:"varint,5,opt,name=digits,proto3,enum=DigitCount,oneof" json:"digits,omitempty"`
	Type      *OtpType    `protobuf:"varint,6,opt,name=type,proto3,enum=OtpType,oneof" json:"type,omitempty"`
	Counter   *int64      `protobuf:"varint,7,opt,name=counter,proto3,oneof" json:"counter,omitempty"`
}

func (x *OtpParameters) Reset() {
	*x = OtpParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OtpMigration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtpParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpParameters) ProtoMessage() {}

func (x *OtpParameters) ProtoReflect() protoreflect.Message {
	mi := &file_OtpMigration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpParameters.ProtoReflect.Descriptor instead.
func (*OtpParameters) Descriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{1}
}

func (x *OtpParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *OtpParameters) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OtpParameters) GetIssuer() string {
	if x != nil && x.Issuer != nil {
		return *x.Issuer
	}
	return ""
}

func (x *OtpParameters) GetAlgorithm() Algorithm {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return Algorithm_ALGORITHM_TYPE_UNSPECIFIED
}

func (x *OtpParameters) GetDigits() DigitCount {
	if x != nil && x.Digits != nil {
		return *x.Digits
	}
	return DigitCount_DIGIT_COUNT_UNSPECIFIED
}

func (x *OtpParameters) GetType() OtpType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return OtpType_OTP_TYPE_UNSPECIFIED
}

func (x *OtpParameters) GetCounter() int64 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

var File_OtpMigration_proto protoreflect.FileDescriptor

var file_OtpMigration_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4f, 0x74, 0x70, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x10, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x35, 0x0a, 0x0e, 0x6f, 0x74, 0x70,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x4f, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x0d, 0x6f, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x22, 0x0a, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52, 0x07, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x22, 0xca, 0x02, 0x0a, 0x0d, 0x4f, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x41, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x48, 0x03, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x48, 0x04, 0x52, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e,
	0x4f, 0x74, 0x70, 0x54, 0x79, 0x70, 0x65, 0x48, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x06, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2a, 0x56,
	0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1e, 0x0a, 0x1a, 0x41,
	0x4c, 0x47, 0x4f, 0x52, 0x49, 0x54, 0x48, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x48, 0x41, 0x31, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x10, 0x03, 0x12, 0x07, 0x0a,
	0x03, 0x4d, 0x44, 0x35, 0x10, 0x04, 0x2a, 0x3d, 0x0a, 0x0a, 0x44, 0x69, 0x67, 0x69, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x49, 0x47, 0x49, 0x54, 0x5f, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x49, 0x58, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x49,
	0x47, 0x48, 0x54, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x07, 0x4f, 0x74, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x14, 0x4f, 0x54, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f,
	0x54, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x4f, 0x54, 0x50, 0x10, 0x02, 0x42, 0x18,
	0x5a, 0x16, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x70,
	0x6b, 0x69, 0x6e, 0x2f, 0x74, 0x6f, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OtpMigration_proto_rawDescOnce sync.Once
	file_OtpMigration_proto_rawDescData = file_OtpMigration_proto_rawDesc
)

func file_OtpMigration_proto_rawDescGZIP() []byte {
	file_OtpMigration_proto_rawDescOnce.Do(func() {
		file_OtpMigration_proto_rawDescData = protoimpl.X.CompressGZIP(file_OtpMigration_proto_rawDescData)
	})
	return file_OtpMigration_proto_rawDescData
}

var file_OtpMigration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_OtpMigration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_OtpMigration_proto_goTypes = []interface{}{
	(Algorithm)(0),           // 0: Algorithm
	(DigitCount)(0),          // 1: DigitCount
	(OtpType)(0),             // 2: OtpType
	(*MigrationPayload)(nil), // 3: MigrationPayload
	(*OtpParameters)(nil),    // 4: OtpParameters
}
var file_OtpMigration_proto_depIdxs = []int32{
	4, // 0: MigrationPayload.otp_parameters:type_name -> OtpParameters
	0, // 1: OtpParameters.algorithm:type_name -> Algorithm
	1, // 2: OtpParameters.digits:type_name -> DigitCount
	2, // 3: OtpParameters.type:type_name -> OtpType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_OtpMigration_proto_init() }
func file_OtpMigration_proto_init() {
	if File_OtpMigration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OtpMigration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OtpMigration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtpParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_OtpMigration_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_OtpMigration_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OtpMigration_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OtpMigration_proto_goTypes,
		DependencyIndexes: file_OtpMigration_proto_depIdxs,
		EnumInfos:         file_OtpMigration_proto_enumTypes,
		MessageInfos:      file_OtpMigration_proto_msgTypes,
	}.Build()
	File_OtpMigration_proto = out.File
	file_OtpMigration_proto_rawDesc = nil
	file_OtpMigration_proto_goTypes = nil
	file_OtpMigration_proto_depIdxs = nil
}
